name: Update Profile cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=chartreuse-dark&hide_border=true&card_width=800&include_all_commits=true&count_private=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # layout: normal, compact, donut, donut-vertical, pie
      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=chartreuse-dark&hide_border=true&card_width=800&layout=normal&langs_count=10
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate wakatime card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: username=${{ github.repository_owner }}&theme=chartreuse-dark&hide_border=true&card_width=800
          path: profile/wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pythonLogs pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=pythonLogs&theme=chartreuse-dark&hide_border=true
          path: profile/pythonLogs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate ddcDatabases pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=ddcDatabases&theme=chartreuse-dark&hide_border=true
          path: profile/ddcDatabases.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate DiscordBot pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=DiscordBot&theme=chartreuse-dark&hide_border=true
          path: profile/DiscordBot.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate ReshadeUtils pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=ReshadeUtils&theme=chartreuse-dark&hide_border=true
          path: profile/ReshadeUtils.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Gw2Launcher pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=Gw2Launcher&theme=chartreuse-dark&hide_border=true
          path: profile/Gw2Launcher.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate 802.11ad pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=802.11ad&theme=chartreuse-dark&hide_border=true
          path: profile/802_11ad.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate raspfan.py gist card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: gist
          options: id=1c2d19f1c932de07f26dc1f02e0ee3ec&theme=chartreuse-dark&hide_border=true
          path: profile/raspfan.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
